# Generated by Django 2.2.1 on 2019-08-08 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terms',
            options={'verbose_name': 'Terms and Conditions', 'verbose_name_plural': 'Terms and Conditions'},
        ),
        migrations.RenameField(
            model_name='terms',
            old_name='terms',
            new_name='details',
        ),
    ]
