# Generated by Django 2.2.1 on 2019-08-12 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    def insertData(apps, schema_editor):
        Term = apps.get_model('pages', 'Term')
        term = Term(details="Edit this")
        term.save()
    operations = [
        migrations.RunPython(insertData),
    ]
