# Generated by Django 2.2.1 on 2019-08-08 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190808_1303'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Terms',
            new_name='Term',
        ),
    ]
