# Generated by Django 2.2.1 on 2019-08-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20190808_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
