# Generated by Django 2.2.1 on 2019-05-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('S', 'SUCCESSFUL'), ('P', 'PENDING'), ('F', 'FAILED')], default='P', max_length=1),
        ),
    ]
