# Generated by Django 2.2.1 on 2019-06-19 21:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientaccount',
            options={
                'ordering': ['-created_at']
            },
        ),
        migrations.AlterModelOptions(
            name='deposit',
            options={
                'ordering': ['-created_at']
            },
        ),
        migrations.AlterModelOptions(
            name='savings',
            options={
                'ordering': ['-created_at']
            },
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={
                'ordering': ['-created_at']
            },
        ),
    ]
