# Generated by Django 2.2.1 on 2019-07-11 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20190711_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='transaction',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='transactions.Transaction'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='transactions.Savings'),
        ),
    ]
