# Generated by Django 2.2.1 on 2019-07-11 10:46

from django.db import migrations


class Migration(migrations.Migration):
    '''
    This migration add a constraint which check if deposit type is not null
    It can either have a account_id or a transaction id not both or nor none
    '''

    dependencies = [
        ('transactions', '0003_auto_20190711_0932'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER TABLE transactions_deposit'
            ' ADD CONSTRAINT deposit_type_check CHECK ('
            ' (account_id IS NULL AND transaction_id IS NOT NULL)'
            ' OR '
            '( transaction_id IS NULL AND account_id IS NOT NULL'
            ' ));')
    ]
