# Generated by Django 2.2.1 on 2019-07-15 10:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20190711_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='references',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None),
        ),
    ]
