# Generated by Django 2.2.1 on 2019-07-18 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transaction_amount_payed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savings',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='savings', to=settings.AUTH_USER_MODEL),
        ),
    ]
