# Generated by Django 2.2.1 on 2019-07-25 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_auto_20190724_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount_payed',
            new_name='amount_paid',
        ),
    ]
