# Generated by Django 2.2.1 on 2019-07-31 20:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_auto_20190725_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='references',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='transaction',
            field=models.
            ForeignKey(blank=True,
                       default=None,
                       null=True,
                       on_delete=django.db.models.deletion.CASCADE,
                       related_name='deposits',
                       to='transactions.Transaction'),
        ),
    ]
