# Generated by Django 2.2.1 on 2019-08-15 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_auto_20190725_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='transaction',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='transactions.Transaction'),
        ),
    ]
