# Generated by Django 2.2.1 on 2019-07-18 07:09

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_card_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='card_token',
        ),
        migrations.AddField(
            model_name='user',
            name='card_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                verbose_name='tokenized card details'),
        ),
    ]
