# Generated by Django 2.2.1 on 2019-06-19 21:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={
                'ordering': ['-created_at']
            },
        ),
        migrations.AlterModelOptions(
            name='propertyenquiry',
            options={
                'ordering': ['-created_at']
            },
        ),
        migrations.AlterModelOptions(
            name='propertyinspection',
            options={
                'ordering': ['-created_at']
            },
        ),
        migrations.AlterModelOptions(
            name='propertyreview',
            options={
                'ordering': ['-created_at']
            },
        ),
    ]
