# Generated by Django 2.2.1 on 2019-05-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('B', 'BUILDING'), ('E', 'EMPTY LOT')], default='B', max_length=1),
        ),
    ]
