# Generated by Django 2.2.1 on 2019-06-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20190612_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
