# Generated by Django 2.2.1 on 2019-06-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_viewed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='viewed_at',
            field=models.DateTimeField(),
        ),
    ]
