# Generated by Django 2.2.1 on 2019-06-14 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20190613_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='viewed_at',
        ),
    ]
