# Generated by Django 2.2.1 on 2019-06-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_property_last_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='last_viewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
